// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameop.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameOp struct {
	Op                   int32    `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Param                int32    `protobuf:"varint,2,opt,name=param,proto3" json:"param,omitempty"`
	Extra                string   `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameOp) Reset()         { *m = GameOp{} }
func (m *GameOp) String() string { return proto.CompactTextString(m) }
func (*GameOp) ProtoMessage()    {}
func (*GameOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d8c685c1d7d7b5c, []int{0}
}

func (m *GameOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOp.Unmarshal(m, b)
}
func (m *GameOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOp.Marshal(b, m, deterministic)
}
func (m *GameOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOp.Merge(m, src)
}
func (m *GameOp) XXX_Size() int {
	return xxx_messageInfo_GameOp.Size(m)
}
func (m *GameOp) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOp.DiscardUnknown(m)
}

var xxx_messageInfo_GameOp proto.InternalMessageInfo

func (m *GameOp) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *GameOp) GetParam() int32 {
	if m != nil {
		return m.Param
	}
	return 0
}

func (m *GameOp) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*GameOp)(nil), "msg.GameOp")
}

func init() { proto.RegisterFile("gameop.proto", fileDescriptor_2d8c685c1d7d7b5c) }

var fileDescriptor_2d8c685c1d7d7b5c = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4f, 0xcc, 0x4d,
	0xcd, 0x2f, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x72, 0xe1,
	0x62, 0x73, 0x4f, 0xcc, 0x4d, 0xf5, 0x2f, 0x10, 0xe2, 0xe3, 0x62, 0xca, 0x2f, 0x90, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x2f, 0x10, 0x12, 0xe1, 0x62, 0x2d, 0x48, 0x2c, 0x4a, 0xcc,
	0x95, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x20, 0xd1, 0xd4, 0x8a, 0x92, 0xa2, 0x44, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x08, 0x27, 0x89, 0x0d, 0x6c, 0xa2, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x1f, 0xb6, 0x18, 0x2a, 0x61, 0x00, 0x00, 0x00,
}
