// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loginmsg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginMsg struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af635a5ce6edb41, []int{0}
}

func (m *LoginMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsg.Unmarshal(m, b)
}
func (m *LoginMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsg.Marshal(b, m, deterministic)
}
func (m *LoginMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsg.Merge(m, src)
}
func (m *LoginMsg) XXX_Size() int {
	return xxx_messageInfo_LoginMsg.Size(m)
}
func (m *LoginMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsg proto.InternalMessageInfo

func (m *LoginMsg) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterMsg struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmedPassword    string   `protobuf:"bytes,4,opt,name=confirmed_password,json=confirmedPassword,proto3" json:"confirmed_password,omitempty"`
	Sex                  string   `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMsg) Reset()         { *m = RegisterMsg{} }
func (m *RegisterMsg) String() string { return proto.CompactTextString(m) }
func (*RegisterMsg) ProtoMessage()    {}
func (*RegisterMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af635a5ce6edb41, []int{1}
}

func (m *RegisterMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMsg.Unmarshal(m, b)
}
func (m *RegisterMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMsg.Marshal(b, m, deterministic)
}
func (m *RegisterMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMsg.Merge(m, src)
}
func (m *RegisterMsg) XXX_Size() int {
	return xxx_messageInfo_RegisterMsg.Size(m)
}
func (m *RegisterMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMsg proto.InternalMessageInfo

func (m *RegisterMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterMsg) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterMsg) GetConfirmedPassword() string {
	if m != nil {
		return m.ConfirmedPassword
	}
	return ""
}

func (m *RegisterMsg) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginMsg)(nil), "msg.LoginMsg")
	proto.RegisterType((*RegisterMsg)(nil), "msg.RegisterMsg")
}

func init() { proto.RegisterFile("loginmsg.proto", fileDescriptor_4af635a5ce6edb41) }

var fileDescriptor_4af635a5ce6edb41 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x4f, 0xcf,
	0xcc, 0xcb, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57,
	0xb2, 0xe3, 0xe2, 0xf0, 0x01, 0x09, 0xfb, 0x16, 0xa7, 0x0b, 0x89, 0x71, 0xb1, 0xe5, 0xe6, 0x27,
	0x65, 0xe6, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x52, 0x5c, 0x1c,
	0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60, 0x19, 0x38, 0x5f, 0x69, 0x1a,
	0x23, 0x17, 0x77, 0x50, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x6a, 0x11, 0xc8, 0x0c, 0x21, 0x2e, 0x96,
	0xbc, 0xc4, 0x5c, 0x98, 0x09, 0x60, 0x36, 0x92, 0xb9, 0x4c, 0x38, 0xcd, 0x65, 0x46, 0x35, 0x57,
	0x48, 0x97, 0x4b, 0x28, 0x39, 0x3f, 0x2f, 0x2d, 0xb3, 0x28, 0x37, 0x35, 0x25, 0x1e, 0xae, 0x8a,
	0x05, 0xac, 0x4a, 0x10, 0x2e, 0x13, 0x00, 0x53, 0x2e, 0xc0, 0xc5, 0x5c, 0x9c, 0x5a, 0x21, 0xc1,
	0x0a, 0x96, 0x07, 0x31, 0x93, 0xd8, 0xc0, 0x9e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x9e, 0xb4, 0x61, 0xf6, 0x00, 0x00, 0x00,
}
